@csrf
<div style="display:grid; gap:16px;">
    <div><label for="name">Tên sản phẩm *</label><input id="name" name="name" value="{{ old('name', $product?->name) }}" required style="width:100%; padding:10px;">@error('name')<small class="admin-error">{{ $message }}</small>@enderror</div>
    <div style="display:grid; grid-template-columns:1fr 1fr; gap:16px;"><div><label for="slug">Slug *</label><input id="slug" name="slug" value="{{ old('slug', $product?->slug) }}" required style="width:100%; padding:10px;">@error('slug')<small class="admin-error">{{ $message }}</small>@enderror</div><div><label for="sku">SKU *</label><input id="sku" name="sku" value="{{ old('sku', $product?->sku) }}" required style="width:100%; padding:10px;">@error('sku')<small class="admin-error">{{ $message }}</small>@enderror</div></div>
    <div style="display:grid; grid-template-columns:repeat(3, 1fr); gap:16px;"><div><label for="category_id">Danh mục</label><select id="category_id" name="category_id" style="width:100%; padding:10px;"><option value="">-- Không chọn --</option>@foreach($categories as $category)<option value="{{ $category->id }}" {{ (string) old('category_id', $product?->category_id) === (string) $category->id ? 'selected' : '' }}>{{ $category->name }}</option>@endforeach</select></div><div><label for="material_id">Chất liệu</label><select id="material_id" name="material_id" style="width:100%; padding:10px;"><option value="">-- Không chọn --</option>@foreach($materials as $material)<option value="{{ $material->id }}" {{ (string) old('material_id', $product?->material_id) === (string) $material->id ? 'selected' : '' }}>{{ $material->name }}</option>@endforeach</select></div><div><label for="stock">Tồn kho *</label><input id="stock" type="number" min="0" name="stock" value="{{ old('stock', $product?->stock ?? 0) }}" required style="width:100%; padding:10px;">@error('stock')<small class="admin-error">{{ $message }}</small>@enderror</div></div>
    <div style="display:grid; grid-template-columns:1fr 1fr; gap:16px;"><div><label for="price">Giá *</label><input id="price" type="number" min="0" step="0.01" name="price" value="{{ old('price', $product?->price ?? 0) }}" required style="width:100%; padding:10px;">@error('price')<small class="admin-error">{{ $message }}</small>@enderror</div><div><label for="sale_price">Giá khuyến mãi</label><input id="sale_price" type="number" min="0" step="0.01" name="sale_price" value="{{ old('sale_price', $product?->sale_price) }}" style="width:100%; padding:10px;">@error('sale_price')<small class="admin-error">{{ $message }}</small>@enderror</div></div>
    <div><label for="featured_image">Ảnh đại diện</label><input id="featured_image" name="featured_image" value="{{ old('featured_image', $product?->featured_image) }}" style="width:100%; padding:10px;"></div>
    <div><label for="short_description">Mô tả ngắn</label><textarea id="short_description" name="short_description" rows="3" style="width:100%; padding:10px;">{{ old('short_description', $product?->short_description) }}</textarea></div>
    <div><label for="description">Mô tả chi tiết</label><textarea id="description" name="description" rows="6" style="width:100%; padding:10px;">{{ old('description', $product?->description) }}</textarea></div>
    <fieldset style="border:1px solid #dfe4e8; padding:14px;"><legend>Bộ sưu tập</legend><div style="display:flex; gap:12px; flex-wrap:wrap;">@foreach($collections as $collection)<label><input type="checkbox" name="collection_ids[]" value="{{ $collection->id }}" {{ in_array($collection->id, old('collection_ids', $product?->collections?->pluck('id')->all() ?? [])) ? 'checked' : '' }}> {{ $collection->name }}</label>@endforeach</div></fieldset>
    <div><label for="sort_order">Thứ tự ưu tiên</label><input id="sort_order" type="number" min="0" name="sort_order" value="{{ old('sort_order', $product?->sort_order ?? 0) }}" style="width:160px; padding:10px;"></div>
    <div style="display:flex; gap:18px; flex-wrap:wrap;"><label><input type="hidden" name="featured" value="0"><input type="checkbox" name="featured" value="1" {{ old('featured', $product?->featured) ? 'checked' : '' }}> Sản phẩm nổi bật</label><label><input type="hidden" name="is_new_arrival" value="0"><input type="checkbox" name="is_new_arrival" value="1" {{ old('is_new_arrival', $product?->is_new_arrival) ? 'checked' : '' }}> Hàng mới</label><label><input type="hidden" name="is_bestseller" value="0"><input type="checkbox" name="is_bestseller" value="1" {{ old('is_bestseller', $product?->is_bestseller) ? 'checked' : '' }}> Bán chạy</label><label><input type="hidden" name="is_active" value="0"><input type="checkbox" name="is_active" value="1" {{ old('is_active', $product?->is_active ?? true) ? 'checked' : '' }}> Đang kinh doanh</label></div>
</div>
