@extends('layouts.admin')

@section('content')
<div style="display:grid; gap:20px; max-width:980px;">
<div class="filter-box"><h1>Chỉnh sửa sản phẩm</h1><form method="POST" action="{{ route('admin.products.update', $product) }}" enctype="multipart/form-data">@method('PUT')@include('admin.products._form')<div style="margin-top:20px; display:flex; gap:12px;"><button class="btn btn-primary" type="submit">Cập nhật</button><a class="btn btn-secondary" href="{{ route('admin.products.index') }}">Hủy</a></div></form></div>
<section class="filter-box"><h2>Thư viện ảnh</h2>
@foreach($product->images as $image)<div style="display:flex;gap:10px;margin:10px 0;align-items:center;opacity:{{ $image->is_active ? 1 : .55 }};"><form method="POST" action="{{ route('admin.products.images.update', [$product, $image]) }}" style="display:grid;grid-template-columns:90px 1fr 100px auto auto auto;gap:10px;align-items:center;flex:1;">@csrf @method('PUT')<img src="{{ \App\Support\MediaUrl::resolve($image->image_path) }}" alt="" style="width:80px;height:64px;object-fit:cover"><input name="alt_text" value="{{ $image->alt_text }}" placeholder="Alt text"><input type="number" min="0" name="sort_order" value="{{ $image->sort_order }}"><label><input type="checkbox" name="is_primary" value="1" @checked($image->is_primary)> Ảnh bìa</label><label><input type="hidden" name="is_active" value="0"><input type="checkbox" name="is_active" value="1" @checked($image->is_active)> Hiển thị</label><button class="btn btn-secondary">Lưu</button></form>@if($image->is_active)<form method="POST" action="{{ route('admin.products.images.destroy', [$product, $image]) }}">@csrf @method('DELETE')<button class="btn btn-secondary">Ẩn</button></form>@endif</div>@endforeach
<form method="POST" action="{{ route('admin.products.images.store', $product) }}" enctype="multipart/form-data" style="display:grid;grid-template-columns:2fr 2fr 100px auto auto;gap:10px;margin-top:16px;">@csrf<input name="image_path" placeholder="Đường dẫn ảnh cũ (không bắt buộc)"><input type="file" name="image_upload" accept="image/jpeg,image/png,image/webp"><input name="alt_text" placeholder="Mô tả ảnh"><input type="number" min="0" name="sort_order" value="0"><label><input type="checkbox" name="is_primary" value="1"> Ảnh bìa</label><button class="btn btn-primary">Thêm ảnh</button></form></section>
<section class="filter-box"><h2>Thông số trang sức</h2>
@foreach($product->specifications as $specification)<div style="display:flex;gap:10px;margin:10px 0;opacity:{{ $specification->is_active ? 1 : .55 }};"><form method="POST" action="{{ route('admin.products.specifications.update', [$product, $specification]) }}" style="display:grid;grid-template-columns:1fr 2fr 90px auto auto;gap:10px;flex:1;">@csrf @method('PUT')<input name="label" value="{{ $specification->label }}" required><input name="value" value="{{ $specification->value }}" required><input type="number" min="0" name="sort_order" value="{{ $specification->sort_order }}"><label><input type="hidden" name="is_active" value="0"><input type="checkbox" name="is_active" value="1" @checked($specification->is_active)> Hiển thị</label><button class="btn btn-secondary">Lưu</button></form>@if($specification->is_active)<form method="POST" action="{{ route('admin.products.specifications.destroy', [$product, $specification]) }}">@csrf @method('DELETE')<button class="btn btn-secondary">Ẩn</button></form>@endif</div>@endforeach
<form method="POST" action="{{ route('admin.products.specifications.store', $product) }}" style="display:grid;grid-template-columns:1fr 2fr 90px auto;gap:10px;margin-top:16px;">@csrf<input name="label" required placeholder="VD: Độ tinh khiết"><input name="value" required placeholder="VD: Bạc 925"><input type="number" min="0" name="sort_order" value="0"><button class="btn btn-primary">Thêm thông số</button></form></section>
</div>
@endsection
