@extends('layouts.admin')

@section('content')
<div style="display:grid; gap:20px;">
    @if(session('success'))<div class="admin-success">{{ session('success') }}</div>@endif
    <div style="display:flex; justify-content:space-between; gap:16px; align-items:center; flex-wrap:wrap;"><div><span class="eyebrow">Danh mục hàng hóa</span><h1 style="margin:0;">Sản phẩm</h1></div><a class="btn btn-primary" href="{{ route('admin.products.create') }}">Thêm sản phẩm</a></div>
    <form method="GET" action="{{ route('admin.products.index') }}" class="filter-box" style="display:flex; gap:12px; flex-wrap:wrap; align-items:end;"><div style="flex:1; min-width:200px;"><label for="q">Tìm kiếm</label><input id="q" name="q" value="{{ request('q') }}" placeholder="Tên, SKU hoặc slug" style="width:100%; padding:10px;"></div><div><label for="category_id">Danh mục</label><select id="category_id" name="category_id" style="padding:10px;"><option value="">Tất cả</option>@foreach($categories as $category)<option value="{{ $category->id }}" {{ (string) request('category_id') === (string) $category->id ? 'selected' : '' }}>{{ $category->name }}</option>@endforeach</select></div><div><label for="status">Trạng thái</label><select id="status" name="status" style="padding:10px;"><option value="">Tất cả</option><option value="active" {{ request('status') === 'active' ? 'selected' : '' }}>Đang bán</option><option value="inactive" {{ request('status') === 'inactive' ? 'selected' : '' }}>Ngừng bán</option></select></div><button class="btn btn-secondary" type="submit">Lọc</button></form>
    <div class="filter-box" style="overflow-x:auto;"><table style="width:100%; min-width:850px; border-collapse:collapse;"><thead><tr><th style="text-align:left; padding:10px;">Tên</th><th style="text-align:left; padding:10px;">SKU</th><th style="text-align:left; padding:10px;">Danh mục</th><th style="text-align:right; padding:10px;">Giá</th><th style="text-align:right; padding:10px;">Tồn kho</th><th style="text-align:left; padding:10px;">Trạng thái</th><th style="padding:10px;"></th></tr></thead><tbody>@forelse($products as $product)<tr><td style="padding:10px; border-top:1px solid #e5e7eb;">{{ $product->name }}</td><td style="padding:10px; border-top:1px solid #e5e7eb;">{{ $product->sku }}</td><td style="padding:10px; border-top:1px solid #e5e7eb;">{{ $product->category?->name ?? '-' }}</td><td style="padding:10px; border-top:1px solid #e5e7eb; text-align:right;">{{ number_format((float) $product->price, 0, ',', '.') }}đ</td><td style="padding:10px; border-top:1px solid #e5e7eb; text-align:right;">{{ $product->stock }}</td><td style="padding:10px; border-top:1px solid #e5e7eb;">{{ $product->is_active ? 'Đang bán' : 'Ngừng bán' }}</td><td style="padding:10px; border-top:1px solid #e5e7eb; white-space:nowrap;"><a class="btn btn-secondary" href="{{ route('admin.products.edit', $product) }}">Sửa</a> <a class="btn btn-secondary" href="{{ route('admin.products.variants.index', $product) }}">Biến thể</a><form method="POST" action="{{ route('admin.products.destroy', $product) }}" style="display:inline;" onsubmit="return confirm('Xác nhận xóa/ngừng bán sản phẩm này?');">@csrf @method('DELETE')<button class="btn btn-secondary" type="submit">Xóa</button></form></td></tr>@empty<tr><td colspan="7" style="padding:18px; text-align:center;">Chưa có sản phẩm phù hợp.</td></tr>@endforelse</tbody></table></div>
    {{ $products->links() }}
</div>
@endsection