@csrf
<div style="display:grid;gap:14px">
    @if ($errors->any())
        <div class="admin-error" data-banner-validation-errors role="alert" style="padding:12px 14px;background:#fff1f0;border-radius:8px;">
            <strong>Không thể lưu banner.</strong>
            <ul style="margin:8px 0 0;padding-left:18px;">
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <label>Tiêu đề<input name="title" value="{{ old('title',$banner?->title) }}" style="width:100%"><small>Không bắt buộc đối với banner chỉ hiển thị hình ảnh/video.</small>@error('title')<small data-banner-error="title" style="color:#b42318">{{ $message }}</small>@enderror</label>
    <label>Ảnh hoặc Vimeo video URL<input name="image" value="{{ old('image',$banner?->image) }}" style="width:100%"><small>Với vị trí “Campaign Video”, “Engagement Video” hoặc “High Jewelry Video”, chỉ nhập Vimeo video URL HTTPS, ví dụ: https://vimeo.com/123456789. New Arrivals Campaign, Editorial Gallery, High Jewelry Image, High Jewelry Campaign, High Jewelry Editorial, CZ Editorial, Colored Gemstone Editorial, Pearl Editorial và Wedding Editorial chỉ nhận hình ảnh. Không nhập iframe hoặc mã nhúng.</small>@error('image')<small data-banner-error="image" style="color:#b42318">{{ $message }}</small>@enderror</label>
    <label>Tải ảnh<input type="file" name="image_upload" accept="image/jpeg,image/png,image/webp" style="width:100%"><small>Chỉ dành cho banner hình ảnh. JPEG, PNG hoặc WebP, tối đa 5 MB.</small>@error('image_upload')<small data-banner-error="image_upload" style="color:#b42318">{{ $message }}</small>@enderror</label>
    <label>Liên kết<input name="link" value="{{ old('link',$banner?->link) }}" style="width:100%">@error('link')<small data-banner-error="link" style="color:#b42318">{{ $message }}</small>@enderror</label>
    <label>Vị trí<select name="position"><option value="home" @selected(old('position',$banner?->position)==='home')>Trang chủ</option><option value="home_story" @selected(old('position',$banner?->position)==='home_story')>Campaign Video</option><option value="home_engagement_video" @selected(old('position',$banner?->position)==='home_engagement_video')>Engagement Video</option><option value="home_high_jewelry_video" @selected(old('position',$banner?->position)==='home_high_jewelry_video')>High Jewelry Video</option><option value="home_high_jewelry_image" @selected(old('position',$banner?->position)==='home_high_jewelry_image')>High Jewelry Image</option><option value="home_high_jewelry_campaign" @selected(old('position',$banner?->position)==='home_high_jewelry_campaign')>High Jewelry Campaign</option><option value="home_high_jewelry_editorial" @selected(old('position',$banner?->position)==='home_high_jewelry_editorial')>High Jewelry Editorial</option><option value="home_cz_editorial" @selected(old('position',$banner?->position)==='home_cz_editorial')>CZ Editorial</option><option value="home_colored_gemstone_editorial" @selected(old('position',$banner?->position)==='home_colored_gemstone_editorial')>Colored Gemstone Editorial</option><option value="home_pearl_editorial" @selected(old('position',$banner?->position)==='home_pearl_editorial')>Pearl Editorial</option><option value="home_wedding_editorial" @selected(old('position',$banner?->position)==='home_wedding_editorial')>Wedding Editorial</option><option value="home_wedding_campaign" @selected(old('position',$banner?->position)==='home_wedding_campaign')>Wedding Campaign</option><option value="home_new_arrivals_campaign" @selected(old('position',$banner?->position)==='home_new_arrivals_campaign')>New Arrivals Campaign</option><option value="home_editorial_gallery" @selected(old('position',$banner?->position)==='home_editorial_gallery')>Editorial Gallery</option><option value="catalog" @selected(old('position',$banner?->position)==='catalog')>Danh mục</option><option value="blog" @selected(old('position',$banner?->position)==='blog')>Blog</option></select>@error('position')<small data-banner-error="position" style="color:#b42318">{{ $message }}</small>@enderror</label>
    <label>Thứ tự<input type="number" min="0" name="sort_order" value="{{ old('sort_order',$banner?->sort_order ?? 0) }}">@error('sort_order')<small data-banner-error="sort_order" style="color:#b42318">{{ $message }}</small>@enderror</label>
    <label>Bắt đầu<input type="datetime-local" name="starts_at" value="{{ old('starts_at',$banner?->starts_at?->format('Y-m-d\TH:i')) }}">@error('starts_at')<small data-banner-error="starts_at" style="color:#b42318">{{ $message }}</small>@enderror</label>
    <label>Kết thúc<input type="datetime-local" name="ends_at" value="{{ old('ends_at',$banner?->ends_at?->format('Y-m-d\TH:i')) }}">@error('ends_at')<small data-banner-error="ends_at" style="color:#b42318">{{ $message }}</small>@enderror</label>
    <label><input type="hidden" name="is_active" value="0"><input type="checkbox" name="is_active" value="1" @checked(old('is_active',$banner?->is_active ?? true))> Đang hiển thị</label>
</div>
